version: "3.2"

services:
  # -----------------------------------------------------------
  # SolrWayback
  # -----------------------------------------------------------

  # solrwayback:
  #   build:
  #     context: .
  #   entrypoint: ["sh", "/docker-entrypoint.sh"]
  #   # ports:
  #   #   - "18080:8080"
  #   environment:
  #     # Allow Solr and WARC server locations to be overidden:
  #     - "SOLR_URL=${SOLR_URL:-http://solr:8983/solr/discovery}"
  #     - "WARC_SERVER_PREFIX=${WARC_SERVER_PREFIX:-http://warc-server/}"
  #     - IPFSURL=${IPFSURL:-http://localhost:9500}
  #   # volumes:
  #   #   - ./docker:/docker

  # Solr instance for running tests against
  solr-0:
    image: ukwa/webarchive-discovery-solr:master
    ports:
      - "18983:8983"
    networks:
      - solr

  # Hook to populate the image with test data:
  populate:
    image: ukwa/webarchive-discovery-populate
    # entrypoint: ["/bin/sh","-c"]
    command: "bash /docker/populateTest.sh"
    #command: "ls"
    environment:
      - "SOLR_URL=${SOLR_URL:-http://solr:8983/solr/discovery}"
    volumes:
      - ./docker:/docker
    networks:
      - solr

  IPFS-GO:
    image: ipfs/go-ipfs
    container_name: go-ipf
    # build:
    #   dockerfile: Dockerfile
    #   context: '.'
    #entrypoint: ["tail", "-f", "/docker-entrypoint.sh"]
    ports:
      - "9500:9501"
    volumes:
      - ./docker:/docker
    expose:
      - "7070"


#   solr-1:
#     image: solr:8.7
#     container_name: solr-1
#     ports:
#       - "8981:8983"
#     volumes:
#       - ./conf:/opt/solr-8.7.0/server/solr/webarchive/discovery/conf
#     environment:
#       - ZK_HOST=zoo-1:2181,zoo-2:2181,zoo-3:2181
#     networks:
#       - solr
#     depends_on:
#       - zoo-1
#       - zoo-2
#       - zoo-3
#   #    command:
#   #      - solr-precreate
#   #      - gettingstarted

#   solr-2:
#     image: solr:8.7
#     container_name: solr-2
#     ports:
#       - "8982:8983"
#     environment:
#       - ZK_HOST=zoo-1:2181,zoo-2:2181,zoo-3:2181
#     networks:
#       - solr
#     depends_on:
#       - zoo-1
#       - zoo-2
#       - zoo-3

#   solr-3:
#     image: solr:8.7
#     container_name: solr-3
#     ports:
#       - "8983:8983"
#     environment:
#       - ZK_HOST=zoo-1:2181,zoo-2:2181,zoo-3:2181
#     networks:
#       - solr
#     depends_on:
#       - zoo-1
#       - zoo-2
#       - zoo-3

#   zoo-1:
#     image: zookeeper:3.6
#     container_name: zoo-1
#     restart: always
#     hostname: zoo-1
#     volumes:
#       - zoo1data:/data
#     ports:
#       - 2181:2181
#     environment:
#       ZOO_MY_ID: 1
#       ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zoo-2:2888:3888;2181 server.3=zoo-3:2888:3888;2181
#     networks:
#       - solr

#   zoo-2:
#     image: zookeeper:3.6
#     container_name: zoo-2
#     restart: always
#     hostname: zoo-2
#     volumes:
#       - zoo2data:/data
#     ports:
#       - 2182:2181
#     environment:
#       ZOO_MY_ID: 2
#       ZOO_SERVERS: server.1=zoo-1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zoo-3:2888:3888;2181
#     networks:
#       - solr

#   zoo-3:
#     image: zookeeper:3.6
#     container_name: zoo-3
#     restart: always
#     hostname: zoo-3
#     volumes:
#       - zoo3data:/data
#     ports:
#       - 2183:2181
#     environment:
#       ZOO_MY_ID: 3
#       ZOO_SERVERS: server.1=zoo-1:2888:3888;2181 server.2=zoo-2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181
#     networks:
#       - solr

# networks:
#   solr:

# # persist the zookeeper data in volumes    
# volumes:
#   zoo1data:
#     driver: local
#   zoo2data:
#     driver: local
#   zoo3data:
#     driver: local